[package]
name = "selena/collection-service-tutorial"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Component = "sleitnick/component@^2.4.8"
Signal = "sleitnick/signal@^1"
TableUtil = "sleitnick/table-util@^1"
Observers = "sleitnick/observers@^0.3.3"
